
package com.bronto.api.model;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BrontoSoapApiImplService", targetNamespace = "http://api.bronto.com/v4", wsdlLocation = "https://api.bronto.com/v4?wsdl")
public class BrontoSoapApiImplService
    extends Service
{

    private final static URL BRONTOSOAPAPIIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bronto.api.model.BrontoSoapApiImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.bronto.api.model.BrontoSoapApiImplService.class.getResource(".");
            url = new URL(baseUrl, "https://api.bronto.com/v4?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://api.bronto.com/v4?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BRONTOSOAPAPIIMPLSERVICE_WSDL_LOCATION = url;
    }

    public BrontoSoapApiImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BrontoSoapApiImplService() {
        super(BRONTOSOAPAPIIMPLSERVICE_WSDL_LOCATION, new QName("http://api.bronto.com/v4", "BrontoSoapApiImplService"));
    }

    /**
     * 
     * @return
     *     returns BrontoSoapPortType
     */
    @WebEndpoint(name = "BrontoSoapApiImplPort")
    public BrontoSoapPortType getBrontoSoapApiImplPort() {
        return super.getPort(new QName("http://api.bronto.com/v4", "BrontoSoapApiImplPort"), BrontoSoapPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BrontoSoapPortType
     */
    @WebEndpoint(name = "BrontoSoapApiImplPort")
    public BrontoSoapPortType getBrontoSoapApiImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.bronto.com/v4", "BrontoSoapApiImplPort"), BrontoSoapPortType.class, features);
    }

}
