
package com.bronto.api.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BrontoSoapApiImplService", targetNamespace = "http://api.bronto.com/v4", wsdlLocation = "https://api.bronto.com/v4?wsdl")
public class BrontoSoapApiImplService
    extends Service
{

    private final static URL BRONTOSOAPAPIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BRONTOSOAPAPIIMPLSERVICE_EXCEPTION;
    private final static QName BRONTOSOAPAPIIMPLSERVICE_QNAME = new QName("http://api.bronto.com/v4", "BrontoSoapApiImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.bronto.com/v4?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BRONTOSOAPAPIIMPLSERVICE_WSDL_LOCATION = url;
        BRONTOSOAPAPIIMPLSERVICE_EXCEPTION = e;
    }

    public BrontoSoapApiImplService() {
        super(__getWsdlLocation(), BRONTOSOAPAPIIMPLSERVICE_QNAME);
    }

    public BrontoSoapApiImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BRONTOSOAPAPIIMPLSERVICE_QNAME, features);
    }

    public BrontoSoapApiImplService(URL wsdlLocation) {
        super(wsdlLocation, BRONTOSOAPAPIIMPLSERVICE_QNAME);
    }

    public BrontoSoapApiImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BRONTOSOAPAPIIMPLSERVICE_QNAME, features);
    }

    public BrontoSoapApiImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BrontoSoapApiImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BrontoSoapPortType
     */
    @WebEndpoint(name = "BrontoSoapApiImplPort")
    public BrontoSoapPortType getBrontoSoapApiImplPort() {
        return super.getPort(new QName("http://api.bronto.com/v4", "BrontoSoapApiImplPort"), BrontoSoapPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BrontoSoapPortType
     */
    @WebEndpoint(name = "BrontoSoapApiImplPort")
    public BrontoSoapPortType getBrontoSoapApiImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.bronto.com/v4", "BrontoSoapApiImplPort"), BrontoSoapPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BRONTOSOAPAPIIMPLSERVICE_EXCEPTION!= null) {
            throw BRONTOSOAPAPIIMPLSERVICE_EXCEPTION;
        }
        return BRONTOSOAPAPIIMPLSERVICE_WSDL_LOCATION;
    }

}
