
package com.bronto.api.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BrontoSoapPortType", targetNamespace = "http://api.bronto.com/v4")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BrontoSoapPortType {


    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadLoginsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readLoginsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadLoginsResponse readLogins(
        @WebParam(name = "readLogins", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadLogins parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteLoginsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteLoginsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteLoginsResponse deleteLogins(
        @WebParam(name = "deleteLogins", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteLogins parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddContactsToWorkflowResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addContactsToWorkflowResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddContactsToWorkflowResponse addContactsToWorkflow(
        @WebParam(name = "addContactsToWorkflow", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddContactsToWorkflow parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteDeliveryGroupResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteDeliveryGroupResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteDeliveryGroupResponse deleteDeliveryGroup(
        @WebParam(name = "deleteDeliveryGroup", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteDeliveryGroup parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadApiTokensResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readApiTokensResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadApiTokensResponse readApiTokens(
        @WebParam(name = "readApiTokens", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadApiTokens parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateMessageRulesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateMessageRulesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateMessageRulesResponse updateMessageRules(
        @WebParam(name = "updateMessageRules", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateMessageRules parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteMessageRulesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteMessageRulesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteMessageRulesResponse deleteMessageRules(
        @WebParam(name = "deleteMessageRules", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteMessageRules parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteMessagesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteMessagesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteMessagesResponse deleteMessages(
        @WebParam(name = "deleteMessages", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteMessages parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadListsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readListsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadListsResponse readLists(
        @WebParam(name = "readLists", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadLists parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddUpdateOrderResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addUpdateOrderResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddUpdateOrderResponse addUpdateOrder(
        @WebParam(name = "addUpdateOrder", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddUpdateOrder parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadMessageFoldersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readMessageFoldersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadMessageFoldersResponse readMessageFolders(
        @WebParam(name = "readMessageFolders", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadMessageFolders parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateSMSDeliveriesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateSMSDeliveriesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateSMSDeliveriesResponse updateSMSDeliveries(
        @WebParam(name = "updateSMSDeliveries", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateSMSDeliveries parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateDeliveryGroupResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateDeliveryGroupResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateDeliveryGroupResponse updateDeliveryGroup(
        @WebParam(name = "updateDeliveryGroup", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateDeliveryGroup parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadHeaderFootersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readHeaderFootersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadHeaderFootersResponse readHeaderFooters(
        @WebParam(name = "readHeaderFooters", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadHeaderFooters parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddFieldsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addFieldsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddFieldsResponse addFields(
        @WebParam(name = "addFields", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddFields parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteApiTokensResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteApiTokensResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteApiTokensResponse deleteApiTokens(
        @WebParam(name = "deleteApiTokens", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteApiTokens parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteHeaderFootersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteHeaderFootersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteHeaderFootersResponse deleteHeaderFooters(
        @WebParam(name = "deleteHeaderFooters", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteHeaderFooters parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddToListResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addToListResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddToListResponse addToList(
        @WebParam(name = "addToList", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddToList parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddSMSMessagesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addSMSMessagesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddSMSMessagesResponse addSMSMessages(
        @WebParam(name = "addSMSMessages", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddSMSMessages parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateContentTagsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateContentTagsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateContentTagsResponse updateContentTags(
        @WebParam(name = "updateContentTags", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateContentTags parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadActivitiesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readActivitiesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadActivitiesResponse readActivities(
        @WebParam(name = "readActivities", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadActivities parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteContactsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteContactsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteContactsResponse deleteContacts(
        @WebParam(name = "deleteContacts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteContacts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadConversionsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readConversionsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadConversionsResponse readConversions(
        @WebParam(name = "readConversions", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadConversions parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddDeliveryGroupResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addDeliveryGroupResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddDeliveryGroupResponse addDeliveryGroup(
        @WebParam(name = "addDeliveryGroup", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddDeliveryGroup parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateMessagesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateMessagesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateMessagesResponse updateMessages(
        @WebParam(name = "updateMessages", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateMessages parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateSMSKeywordsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateSMSKeywordsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateSMSKeywordsResponse updateSMSKeywords(
        @WebParam(name = "updateSMSKeywords", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateSMSKeywords parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadContactsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readContactsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadContactsResponse readContacts(
        @WebParam(name = "readContacts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadContacts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadRecentOutboundActivitiesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readRecentOutboundActivitiesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadRecentOutboundActivitiesResponse readRecentOutboundActivities(
        @WebParam(name = "readRecentOutboundActivities", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadRecentOutboundActivities parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddContentTagsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addContentTagsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddContentTagsResponse addContentTags(
        @WebParam(name = "addContentTags", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddContentTags parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateDeliveriesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateDeliveriesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateDeliveriesResponse updateDeliveries(
        @WebParam(name = "updateDeliveries", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateDeliveries parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteSMSMessagesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteSMSMessagesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteSMSMessagesResponse deleteSMSMessages(
        @WebParam(name = "deleteSMSMessages", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteSMSMessages parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddSMSKeywordsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addSMSKeywordsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddSMSKeywordsResponse addSMSKeywords(
        @WebParam(name = "addSMSKeywords", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddSMSKeywords parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadWorkflowsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readWorkflowsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadWorkflowsResponse readWorkflows(
        @WebParam(name = "readWorkflows", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadWorkflows parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateApiTokensResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateApiTokensResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateApiTokensResponse updateApiTokens(
        @WebParam(name = "updateApiTokens", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateApiTokens parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadAccountsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readAccountsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadAccountsResponse readAccounts(
        @WebParam(name = "readAccounts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadAccounts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddToSMSKeywordResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addToSMSKeywordResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddToSMSKeywordResponse addToSMSKeyword(
        @WebParam(name = "addToSMSKeyword", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddToSMSKeyword parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddListsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addListsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddListsResponse addLists(
        @WebParam(name = "addLists", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddLists parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadDeliveryRecipientsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readDeliveryRecipientsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadDeliveryRecipientsResponse readDeliveryRecipients(
        @WebParam(name = "readDeliveryRecipients", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadDeliveryRecipients parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.RemoveFromListResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "removeFromListResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RemoveFromListResponse removeFromList(
        @WebParam(name = "removeFromList", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        RemoveFromList parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadRecentInboundActivitiesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readRecentInboundActivitiesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadRecentInboundActivitiesResponse readRecentInboundActivities(
        @WebParam(name = "readRecentInboundActivities", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadRecentInboundActivities parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadSMSKeywordsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readSMSKeywordsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadSMSKeywordsResponse readSMSKeywords(
        @WebParam(name = "readSMSKeywords", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadSMSKeywords parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadSegmentsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readSegmentsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadSegmentsResponse readSegments(
        @WebParam(name = "readSegments", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadSegments parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddDeliveriesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addDeliveriesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddDeliveriesResponse addDeliveries(
        @WebParam(name = "addDeliveries", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddDeliveries parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddContactEventResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addContactEventResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddContactEventResponse addContactEvent(
        @WebParam(name = "addContactEvent", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddContactEvent parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddContactsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addContactsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddContactsResponse addContacts(
        @WebParam(name = "addContacts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddContacts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteDeliveriesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteDeliveriesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteDeliveriesResponse deleteDeliveries(
        @WebParam(name = "deleteDeliveries", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteDeliveries parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param apiToken
     * @return
     *     returns java.lang.String
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://api.bronto.com/v4", className = "com.bronto.api.model.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://api.bronto.com/v4", className = "com.bronto.api.model.LoginResponse")
    public String login(
        @WebParam(name = "apiToken", targetNamespace = "")
        String apiToken)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddOrUpdateDeliveryGroupResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addOrUpdateDeliveryGroupResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddOrUpdateDeliveryGroupResponse addOrUpdateDeliveryGroup(
        @WebParam(name = "addOrUpdateDeliveryGroup", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddOrUpdateDeliveryGroup parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteOrdersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteOrdersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteOrdersResponse deleteOrders(
        @WebParam(name = "deleteOrders", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteOrders parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddOrUpdateOrdersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addOrUpdateOrdersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddOrUpdateOrdersResponse addOrUpdateOrders(
        @WebParam(name = "addOrUpdateOrders", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddOrUpdateOrders parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateMessageFoldersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateMessageFoldersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateMessageFoldersResponse updateMessageFolders(
        @WebParam(name = "updateMessageFolders", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateMessageFolders parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddOrUpdateContactsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addOrUpdateContactsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddOrUpdateContactsResponse addOrUpdateContacts(
        @WebParam(name = "addOrUpdateContacts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddOrUpdateContacts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadDeliveriesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readDeliveriesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadDeliveriesResponse readDeliveries(
        @WebParam(name = "readDeliveries", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadDeliveries parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadSMSDeliveriesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readSMSDeliveriesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadSMSDeliveriesResponse readSMSDeliveries(
        @WebParam(name = "readSMSDeliveries", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadSMSDeliveries parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadContentTagsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readContentTagsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadContentTagsResponse readContentTags(
        @WebParam(name = "readContentTags", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadContentTags parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateListsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateListsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateListsResponse updateLists(
        @WebParam(name = "updateLists", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateLists parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddAccountsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addAccountsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddAccountsResponse addAccounts(
        @WebParam(name = "addAccounts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddAccounts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteContentTagsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteContentTagsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteContentTagsResponse deleteContentTags(
        @WebParam(name = "deleteContentTags", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteContentTags parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteListsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteListsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteListsResponse deleteLists(
        @WebParam(name = "deleteLists", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteLists parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddMessagesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addMessagesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddMessagesResponse addMessages(
        @WebParam(name = "addMessages", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddMessages parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.RemoveFromSMSKeywordResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "removeFromSMSKeywordResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RemoveFromSMSKeywordResponse removeFromSMSKeyword(
        @WebParam(name = "removeFromSMSKeyword", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        RemoveFromSMSKeyword parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddHeaderFootersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addHeaderFootersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddHeaderFootersResponse addHeaderFooters(
        @WebParam(name = "addHeaderFooters", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddHeaderFooters parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadFieldsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readFieldsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadFieldsResponse readFields(
        @WebParam(name = "readFields", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadFields parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteFromDeliveryGroupResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteFromDeliveryGroupResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteFromDeliveryGroupResponse deleteFromDeliveryGroup(
        @WebParam(name = "deleteFromDeliveryGroup", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteFromDeliveryGroup parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateFieldsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateFieldsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateFieldsResponse updateFields(
        @WebParam(name = "updateFields", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateFields parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddMessageRulesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addMessageRulesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddMessageRulesResponse addMessageRules(
        @WebParam(name = "addMessageRules", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddMessageRules parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ClearListsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "clearListsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ClearListsResponse clearLists(
        @WebParam(name = "clearLists", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ClearLists parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddMessageFoldersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addMessageFoldersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddMessageFoldersResponse addMessageFolders(
        @WebParam(name = "addMessageFolders", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddMessageFolders parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteAccountsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteAccountsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteAccountsResponse deleteAccounts(
        @WebParam(name = "deleteAccounts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteAccounts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadMessagesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readMessagesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadMessagesResponse readMessages(
        @WebParam(name = "readMessages", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadMessages parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateSMSMessagesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateSMSMessagesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateSMSMessagesResponse updateSMSMessages(
        @WebParam(name = "updateSMSMessages", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateSMSMessages parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadMessageRulesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readMessageRulesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadMessageRulesResponse readMessageRules(
        @WebParam(name = "readMessageRules", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadMessageRules parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteSMSKeywordsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteSMSKeywordsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteSMSKeywordsResponse deleteSMSKeywords(
        @WebParam(name = "deleteSMSKeywords", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteSMSKeywords parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddConversionResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addConversionResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddConversionResponse addConversion(
        @WebParam(name = "addConversion", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddConversion parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateAccountsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateAccountsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateAccountsResponse updateAccounts(
        @WebParam(name = "updateAccounts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateAccounts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddLoginsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addLoginsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddLoginsResponse addLogins(
        @WebParam(name = "addLogins", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddLogins parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteMessageFoldersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteMessageFoldersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteMessageFoldersResponse deleteMessageFolders(
        @WebParam(name = "deleteMessageFolders", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteMessageFolders parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateHeaderFootersResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateHeaderFootersResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateHeaderFootersResponse updateHeaderFooters(
        @WebParam(name = "updateHeaderFooters", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateHeaderFooters parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateContactsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateContactsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateContactsResponse updateContacts(
        @WebParam(name = "updateContacts", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateContacts parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadDeliveryGroupsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readDeliveryGroupsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadDeliveryGroupsResponse readDeliveryGroups(
        @WebParam(name = "readDeliveryGroups", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadDeliveryGroups parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddToDeliveryGroupResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addToDeliveryGroupResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddToDeliveryGroupResponse addToDeliveryGroup(
        @WebParam(name = "addToDeliveryGroup", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddToDeliveryGroup parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddSMSDeliveriesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addSMSDeliveriesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddSMSDeliveriesResponse addSMSDeliveries(
        @WebParam(name = "addSMSDeliveries", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddSMSDeliveries parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteSMSDeliveriesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteSMSDeliveriesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteSMSDeliveriesResponse deleteSMSDeliveries(
        @WebParam(name = "deleteSMSDeliveries", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteSMSDeliveries parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.DeleteFieldsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteFieldsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteFieldsResponse deleteFields(
        @WebParam(name = "deleteFields", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        DeleteFields parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.AddApiTokensResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "addApiTokensResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddApiTokensResponse addApiTokens(
        @WebParam(name = "addApiTokens", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        AddApiTokens parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadSMSMessagesResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readSMSMessagesResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadSMSMessagesResponse readSMSMessages(
        @WebParam(name = "readSMSMessages", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadSMSMessages parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.UpdateLoginsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "updateLoginsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateLoginsResponse updateLogins(
        @WebParam(name = "updateLogins", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        UpdateLogins parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param parameters
     * @param sessionHeader
     * @return
     *     returns com.bronto.api.model.ReadWebformsResponse
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "readWebformsResponse", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ReadWebformsResponse readWebforms(
        @WebParam(name = "readWebforms", targetNamespace = "http://api.bronto.com/v4", partName = "parameters")
        ReadWebforms parameters,
        @WebParam(name = "sessionHeader", targetNamespace = "http://api.bronto.com/v4", header = true, partName = "sessionHeader")
        SessionHeader sessionHeader)
        throws ApiException_Exception
    ;

}
